-- 1. Secuencias
create sequence product_sku_seq start with 1 increment by 1;

-- 2. Tablas
create table brands
(
    id         bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone,
    name       varchar(100)                not null unique,
    slug       varchar(150)                not null unique,
    created_by varchar(255),
    logo_url   TEXT,
    updated_by varchar(255),
    primary key (id)
);
create table categories
(
    id         bigint generated by default as identity,
    created_at timestamp(6) with time zone not null,
    parent_id  bigint,
    updated_at timestamp(6) with time zone,
    name       varchar(100)                not null unique,
    slug       varchar(150)                not null unique,
    created_by varchar(255),
    updated_by varchar(255),
    primary key (id)
);
create table invoices
(
    id           bigint generated by default as identity,
    total_amount numeric(15, 2),
    created_at   timestamp(6) with time zone not null,
    order_id     bigint                      not null,
    updated_at   timestamp(6) with time zone,
    created_by   varchar(255),
    hash_code    varchar(255) unique,
    number       varchar(20),
    pdf_url      TEXT,
    serie        varchar(10),
    status       varchar(30) check (status in ('PENDIENTE', 'EMITIDO', 'CANCELADO', 'ERROR')),
    type         varchar(30) check (type in ('BOLETA', 'FACTURA')),
    updated_by   varchar(255),
    primary key (id)
);
create table order_addresses
(
    id                 bigint generated by default as identity,
    order_id           bigint       not null unique,
    contact_doc_number varchar(20)  not null,
    contact_doc_type   varchar(10)  not null check (contact_doc_type in ('DNI', 'RUC', 'CE')),
    address_line       varchar(255) not null,
    contact_first_name varchar(255) not null,
    contact_last_name  varchar(255) not null,
    contact_phone      varchar(30)  not null,
    department         varchar(100) not null,
    district           varchar(100) not null,
    province           varchar(100) not null,
    reference          varchar(255),
    primary key (id)
);
create table order_items
(
    id                    bigint generated by default as identity,
    price_snapshot        numeric(15, 2) not null,
    quantity              integer        not null,
    order_id              bigint         not null,
    product_id            bigint         not null,
    sku_snapshot          varchar(10)    not null,
    part_number_snapshot  varchar(255)   not null,
    product_name_snapshot varchar(255)   not null,
    primary key (id)
);
create table orders
(
    id                  bigint generated by default as identity,
    total_price         numeric(15, 2)              not null,
    user_id             bigint,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone,
    customer_doc_number varchar(20)                 not null,
    customer_doc_type   varchar(10)                 not null check (customer_doc_type in ('DNI', 'RUC', 'CE')),
    delivery_type       varchar(30)                 not null check (delivery_type in ('A_DOMICILIO', 'RECOJO_EN_TIENDA')),
    payment_method      varchar(30)                 not null check (payment_method in ('TARJETA', 'YAPE', 'PAGO_EFECTIVO')),
    status              varchar(30)                 not null check (status in
                                                                    ('PENDIENTE', 'CONFIRMADO', 'PREPARANDO', 'ENVIADO',
                                                                     'ENTREGADO', 'CANCELADO')),
    order_code          varchar(100)                not null unique,
    admin_notes         TEXT,
    created_by          varchar(255),
    customer_email      varchar(255)                not null,
    customer_first_name varchar(255)                not null,
    customer_last_name  varchar(255)                not null,
    customer_phone      varchar(30)                 not null,
    updated_by          varchar(255),
    primary key (id)
);
create table product_images
(
    id         bigint generated by default as identity,
    position   integer      not null,
    product_id bigint       not null,
    alt_text   varchar(255),
    public_id  varchar(255) not null,
    url        TEXT         not null,
    primary key (id)
);
create table products
(
    id             bigint generated by default as identity,
    original_price numeric(15, 2),
    price          numeric(15, 2)              not null,
    stock          integer                     not null,
    sku            varchar(10)                 not null unique,
    brand_id       bigint                      not null,
    category_id    bigint                      not null,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone,
    created_by     varchar(255),
    description    TEXT,
    name           varchar(255)                not null unique,
    part_number    varchar(255) unique,
    slug           varchar(255)                not null unique,
    status         varchar(30)                 not null check (status in ('ACTIVO', 'INACTIVO')),
    updated_by     varchar(255),
    specifications jsonb,
    primary key (id)
);
create table user_addresses
(
    id                 bigint generated by default as identity,
    is_default         boolean                     not null,
    user_id            bigint                      not null,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone,
    address_line       varchar(255),
    contact_first_name varchar(255),
    contact_last_name  varchar(255),
    contact_phone      varchar(30),
    created_by         varchar(255),
    department         varchar(100),
    district           varchar(100),
    province           varchar(100),
    reference          varchar(255),
    updated_by         varchar(255),
    primary key (id)
);
create table users
(
    id              bigint generated by default as identity,
    enabled         boolean                     not null,
    created_at      timestamp(6) with time zone not null,
    updated_at      timestamp(6) with time zone,
    document_number varchar(20),
    phone           varchar(30),
    first_name      varchar(100),
    last_name       varchar(100),
    created_by      varchar(255),
    document_type   varchar(10) check (document_type in ('DNI', 'RUC', 'CE')),
    email           varchar(255)                not null unique,
    password_hash   varchar(255)                not null,
    role            varchar(30)                 not null check (role in ('ADMIN', 'CLIENTE')),
    updated_by      varchar(255),
    primary key (id)
);

-- 3. Restricciones de clave foránea
alter table if exists categories
    add constraint FK_cat_parent foreign key (parent_id) references categories;
alter table if exists invoices
    add constraint FK_inv_order foreign key (order_id) references orders;
alter table if exists order_addresses
    add constraint FK_ord_addr_order foreign key (order_id) references orders;
alter table if exists order_items
    add constraint FK_ord_items_order foreign key (order_id) references orders;
alter table if exists order_items
    add constraint FK_ord_items_prod foreign key (product_id) references products;
alter table if exists orders
    add constraint FK_orders_user foreign key (user_id) references users;
alter table if exists product_images
    add constraint FK_prod_img_prod foreign key (product_id) references products;
alter table if exists products
    add constraint FK_prod_brand foreign key (brand_id) references brands;
alter table if exists products
    add constraint FK_prod_cat foreign key (category_id) references categories;
alter table if exists user_addresses
    add constraint FK_user_addr_user foreign key (user_id) references users;

-- 4. Índices de Rendimiento
create index idx_categories_parent_id on categories (parent_id);
create index idx_invoices_order_id on invoices (order_id);
create index idx_order_items_order_id on order_items (order_id);
create index idx_order_items_product_id on order_items (product_id);
create index idx_orders_user_id on orders (user_id);
create index idx_product_images_product_id on product_images (product_id);
create index idx_products_brand_id on products (brand_id);
create index idx_products_category_id on products (category_id);
create index idx_user_addresses_user_id on user_addresses (user_id);
