-- 1. Crear la tabla de Tiendas
create table stores
(
    id           bigint generated by default as identity,
    name         varchar(255)                not null,
    address_line varchar(255)                not null,
    department   varchar(100)                not null,
    district     varchar(100)                not null,
    province     varchar(100)                not null,
    active       boolean                     not null,

    created_by   varchar(255),
    updated_by   varchar(255),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone,
    primary key (id)
);

-- 2. Alterar la tabla de Órdenes para vincular analíticamente la Tienda
alter table if exists orders
    add column store_id bigint;

alter table if exists orders
    add constraint fk_orders_store foreign key (store_id) references stores (id);

-- 3. Crear índice para optimizar consultas de analítica y joins por Tienda
create index idx_orders_store_id on orders (store_id);

-- 4. Modificar la columna payment_method para permitir nulos provisionales (Nivel Pasarela/MercadoPago)
alter table if exists orders
    alter column payment_method drop not null;

-- 5. Crear la secuencia correlativa para la generación segura de códigos de pedido
create sequence order_code_seq start with 1 increment by 1;
